version: '3'

services:
  flask-backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./ppt_templates:/app/ppt_templates
    environment:
      - PORT=5000
      - DEBUG=False
      - ALIYUN_API_KEY=${ALIYUN_API_KEY}
    restart: unless-stopped 